"""add_phase_3_matching_data_model

Revision ID: 111f6ef2e07c
Revises: c867767cba7e
Create Date: 2026-08-23 21:19:50.237549
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "111f6ef2e07c"
down_revision: str | None = "c867767cba7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_versions",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("template_sha256", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompt_versions_name"), "prompt_versions", ["name"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_log_user_created", "audit_log", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False)
    op.create_table(
        "job_descriptions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("failure_code", sa.String(length=32), nullable=True),
        sa.Column("extractor_version", sa.String(length=32), nullable=True),
        sa.Column("is_fixture", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_descriptions_user_id"), "job_descriptions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_job_descriptions_user_sha256", "job_descriptions", ["user_id", "sha256"], unique=True
    )
    op.create_table(
        "match_runs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=False),
        sa.Column("job_description_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("scoring_version", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("score_if_trusted", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("impact_delta", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("requirement_count", sa.Integer(), nullable=True),
        sa.Column("unmet_required_count", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("narrative", sa.Text(), nullable=True),
        sa.Column("failure_code", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_description_id"], ["job_descriptions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["prompt_version_id"], ["prompt_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_match_runs_dedup",
        "match_runs",
        ["resume_id", "job_description_id", "prompt_version_id", "scoring_version"],
        unique=True,
    )
    op.create_index(
        op.f("ix_match_runs_job_description_id"), "match_runs", ["job_description_id"], unique=False
    )
    op.create_index(op.f("ix_match_runs_resume_id"), "match_runs", ["resume_id"], unique=False)
    op.create_index(op.f("ix_match_runs_user_id"), "match_runs", ["user_id"], unique=False)
    op.create_table(
        "requirements",
        sa.Column("job_description_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("necessity", sa.String(length=16), nullable=False),
        sa.Column("criticality", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("evidence_start", sa.Integer(), nullable=False),
        sa.Column("evidence_end", sa.Integer(), nullable=False),
        sa.Column("evidence_quote", sa.Text(), nullable=False),
        sa.Column("evidence_page", sa.Integer(), nullable=True),
        sa.Column("evidence_bbox_x0", sa.Float(), nullable=True),
        sa.Column("evidence_bbox_y0", sa.Float(), nullable=True),
        sa.Column("evidence_bbox_x1", sa.Float(), nullable=True),
        sa.Column("evidence_bbox_y1", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_description_id"], ["job_descriptions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_requirements_job_description_id"),
        "requirements",
        ["job_description_id"],
        unique=False,
    )
    op.create_index(
        "ix_requirements_job_ordinal",
        "requirements",
        ["job_description_id", "ordinal"],
        unique=True,
    )
    op.create_table(
        "llm_calls",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("match_run_id", sa.Uuid(), nullable=True),
        sa.Column("job_description_id", sa.Uuid(), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("stop_reason", sa.String(length=32), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_description_id"], ["job_descriptions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["match_run_id"], ["match_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["prompt_version_id"], ["prompt_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_llm_calls_user_created", "llm_calls", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "claims",
        sa.Column("match_run_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("met", sa.Boolean(), nullable=False),
        sa.Column("match_type", sa.String(length=16), nullable=False),
        sa.Column("satisfaction", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("corroboration", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("integrity_factor", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("evidence_quality", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("weight_applied", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("contribution", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("primary_evidence_span_id", sa.Uuid(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("adjacency_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "met = false OR primary_evidence_span_id IS NOT NULL",
            name="ck_claims_met_has_primary_evidence",
        ),
        sa.ForeignKeyConstraint(["match_run_id"], ["match_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["primary_evidence_span_id"], ["text_spans.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["requirement_id"], ["requirements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_claims_match_requirement", "claims", ["match_run_id", "requirement_id"], unique=True
    )
    op.create_index(op.f("ix_claims_match_run_id"), "claims", ["match_run_id"], unique=False)
    op.create_index(op.f("ix_claims_requirement_id"), "claims", ["requirement_id"], unique=False)
    op.create_table(
        "claim_evidence",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("span_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["span_id"], ["text_spans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("claim_id", "span_id"),
    )
    op.create_table(
        "claim_findings",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("claim_id", "finding_id"),
    )
    op.add_column(
        "resumes",
        sa.Column("is_fixture", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "is_fixture")
    op.drop_table("claim_findings")
    op.drop_table("claim_evidence")
    op.drop_index(op.f("ix_claims_requirement_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_match_run_id"), table_name="claims")
    op.drop_index("ix_claims_match_requirement", table_name="claims")
    op.drop_table("claims")
    op.drop_index("ix_llm_calls_user_created", table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index("ix_requirements_job_ordinal", table_name="requirements")
    op.drop_index(op.f("ix_requirements_job_description_id"), table_name="requirements")
    op.drop_table("requirements")
    op.drop_index(op.f("ix_match_runs_user_id"), table_name="match_runs")
    op.drop_index(op.f("ix_match_runs_resume_id"), table_name="match_runs")
    op.drop_index(op.f("ix_match_runs_job_description_id"), table_name="match_runs")
    op.drop_index("ix_match_runs_dedup", table_name="match_runs")
    op.drop_table("match_runs")
    op.drop_index("ix_job_descriptions_user_sha256", table_name="job_descriptions")
    op.drop_index(op.f("ix_job_descriptions_user_id"), table_name="job_descriptions")
    op.drop_table("job_descriptions")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_user_created", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_prompt_versions_name"), table_name="prompt_versions")
    op.drop_table("prompt_versions")
    # ### end Alembic commands ###
