import uuid
from datetime import UTC, datetime

from sqlalchemy import DateTime, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Declarative base that Alembic autogenerate compares the live schema against."""


def new_uuid() -> uuid.UUID:
    return uuid.uuid4()


def utcnow() -> datetime:
    return datetime.now(UTC)


class Identified:
    """A UUID primary key generated by the application, not the database.

    Client-side generation lets the worker and the API refer to a row before it is
    committed, and keeps the same code path under SQLite in tests as under Postgres.
    """

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=new_uuid)


class Timestamped:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
